services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-blog_db}
  pg:
    image: postgres
    environment:
      - POSTGRES_DB=${PG_DB:-blog_db}
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-admin}
    restart: always
    ports:
      - '5432:5432'
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - pg
  blog:
    container_name: blogs-api-nest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    build: .
    restart: always
    ports:
      - '4000:4000'
      - '9229:9229'
    environment:
      - PORT=4000
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=blog_db
      - DB_HOST=mongodb://mongodb:27017
      - INCLUDE_TESTING_MODULE=true
      - JWT_SECRET=cat
      - LOGIN=admin
      - PASSWORD=qwerty
      - JWT_REFRESH_SECRET=dog
      - TTL_RATE_LIMIT=10
      - NUMBER_RATE_LIMIT=5
      - PG_DB=blog_db
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PG_PORT=5432
      - PG_HOST=pg
    depends_on:
      - mongodb
      - pg
