filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/nest.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]